// <auto-generated />
namespace Kookaburra.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class accounttrialexpirydays : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(accounttrialexpirydays));
        
        string IMigrationMetadata.Id
        {
            get { return "201711250320110_accounttrialexpirydays"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
